### PR TITLE
Copy patch from ign-math6-release

### PR DESCRIPTION
**Pull request by scpeters**
debbuild currently fails: https://github.com/ignition-tooling/release-tools/pull/607#issuecomment-1001699495

> * https://build.osrfoundation.org/job/ignition-garden-nightly-scheduler/55/
> * https://build.osrfoundation.org/job/ign-math7-debbuilder/286/
> * https://build.osrfoundation.org/job/ign-math7-debbuilder/287/

[Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/286/)

~~~
patching file src/Pose_TEST.cc
Hunk #1 FAILED at 184.
1 out of 1 hunk FAILED
~~~

needed for https://github.com/ignition-tooling/release-tools/issues/574

### CODE REVIEW

**Comment by scpeters** [comment]
testing with this branch:

[Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/288/) https://build.osrfoundation.org/job/ign-math7-debbuilder/288/

**Comment by chapulina** [comment]
Still failing :thinking: 

```
patching file src/Pose_TEST.cc
Hunk #1 FAILED at 152.
1 out of 1 hunk FAILED
```

**Comment by scpeters** [comment]
> Still failing 🤔
> 
> ```
> patching file src/Pose_TEST.cc
> Hunk #1 FAILED at 152.
> 1 out of 1 hunk FAILED
> ```

trying again

[Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/289/) https://build.osrfoundation.org/job/ign-math7-debbuilder/289/

**Comment by scpeters** [comment]
> > Still failing 🤔
> > ```
> > patching file src/Pose_TEST.cc
> > Hunk #1 FAILED at 152.
> > 1 out of 1 hunk FAILED
> > ```
> 
> trying again
> 
> [Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/289/) https://build.osrfoundation.org/job/ign-math7-debbuilder/289/

success!

**Review by chapulina — APPROVED** [review]

**Pull request merged**
