### PR TITLE
Port ruby and python from ign-math6

### PR DESCRIPTION
**Pull request by chapulina**
Port these PRs:

* https://github.com/ignition-release/ign-math6-release/pull/6
* https://github.com/ignition-release/ign-math6-release/pull/7
* https://github.com/ignition-release/ign-math6-release/pull/9

Needed by

* https://github.com/ignitionrobotics/ign-gazebo/pull/1367

### CODE REVIEW

**Comment by chapulina** [comment]
Test build: [Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/440/)

**Comment by mjcarroll** [comment]
```
[0mTesting with python3.8:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ignition_math7'
[33mautopkgtest [01:57:32]: test autodep8-python3: -----------------------]
[0m[33mautopkgtest [01:57:32]: test autodep8-python3:  - - - - - - - - - - results - - - - - - - - - -
[0mautodep8-python3     FAIL non-zero exit status 1
```

**Comment by chapulina** [comment]
Ported more changes from `ign-math6`, new test build: [Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/443/)

**Comment by mjcarroll** [comment]
Still grumpy, same issue.

**Comment by chapulina** [comment]
The failing check has been recently added in 

* https://github.com/ignition-tooling/release-tools/pull/638

No `ign-math6` releases have been made since, so the same problem may be happening there.

@j-rivero , any guidance here?

**Comment by j-rivero** [comment]
> The failing check has been recently added in
> 
>     *

You are almost there, just suffering a bite from the autopkgtest auto (double auto) generation of tests for python. That tool is generating broken tests for our cases since it can not find a customized tests. I did two things:

 * Add the missing symlinks so we are using the autopkgtest that we have under `ubuntu/debian/tests/*` in [14184c1](https://github.com/ignition-release/ign-math7-release/pull/5/commits/14184c1d207942aba7adcd7dd4444694a1b73e37)
 * Triggered a new build [Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/444/)
 * Disable the auto-generation-of-python-tests in autopkgtest https://github.com/ignition-tooling/release-tools/pull/658

**Comment by chapulina** [comment]
Thaaaaanks @j-rivero ! :pray:

**Comment by scpeters** [comment]
bionic debs are unstable:

* [Build Status](https://build.osrfoundation.org/job/ign-math7-debbuilder/446/) https://build.osrfoundation.org/job/ign-math7-debbuilder/446/

I think the `bionic/debian` folder needs some symlinks to the new `.install` files

**Comment by chapulina** [comment]
Ahh we need to remove the python packages from Bionic, i.e. https://github.com/ignition-release/ign-math6-release/pull/8

**Comment by chapulina** [comment]
* See https://github.com/ignition-release/ign-math7-release/pull/6

**Pull request merged**
